apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: python-rest-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: python-rest-api
  policy:
    semver:
      range: '>= 1.0.0 <2.0.0'
