apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: default
spec:
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: docker.io/shital1999/python-rest-api:latest # Use "latest" for automatic updates
        imagePullPolicy: IfNotPresent # Pull and replace image for updates
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
