---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: python
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: python
  policy:
    semver:
      range: 0.1.0
