---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: python-rest-api
  namespace: flux-system
spec:
  image: docker.io/shital1999/python-rest-api:1.0.0
  interval: 1m0s
